### ISSUE TITLE
go_vncdriver was installed without OpenGL support

### ISSUE THREAD

**Issue by mtmvu** [openai/go-vncdriver#10]
Hi,
I ran into this problem even after installing all the depedencies.
`build.sh` gives me:

> ./build.sh: 60: ./build.sh: [[: not found
Env info:
export CGO_LDFLAGS='/usr/lib/x86_64-linux-gnu/libjpeg.so -L/home/ubuntu/miniconda3/envs/myUniverse/lib -lpython3.5m'
export CGO_CFLAGS='-I/home/ubuntu/miniconda3/envs/myUniverse/lib/python3.5/site-packages/numpy/core/include -I/home/ubuntu/miniconda3/envs/myUniverse/include/python3.5m'
Running build with OpenGL rendering.
Building with OpenGL: go build -buildmode=c-shared -o go_vncdriver.so. (Set GO_VNCDRIVER_NOGL to build without OpenGL.)

Then install `go-vncdriver` again.
And when i run the exact example from the universe readme, i got the error mentionned above.

I have no ideas where this could come from

**Comment by tlbtlbtlb** [comment]
You should be able to work around this by running `bash build.sh` instead of `./build.sh`.

**Comment by jeremyschlatter** [comment]
Sorry about that. This is fixed in d5861f1ce93c8508295d158fae71fd9aba943009.

**Comment by jeremyschlatter** [comment]
Marking as resolved. I think the `[[: not found` error, which is now fixed, actually didn't cause a problem here<sup>[1]</sup>. You just need to run a different command post-installation from what we had in the README. See 2c2f651c2498c5f3d44c23e5feef97a3b01df975.

[1] There was a bug in the build script, but the bug just caused the script to skip an `if` clause that it would have skipped anyway.
