### ISSUE TITLE
Remove go-vncdriver

### ISSUE THREAD

**Issue by scriptingislife** [openai/go-vncdriver#11]
I am trying to set up Universe with OpenAI but am having trouble with go-vncdriver. When I run the given test program, named trial.py in this case, I'm given this error:
`Traceback (most recent call last):
  File "trial.py", line 11, in <module>
    env.render()
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 192, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 342, in _render
    return self.env.render(mode, close)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 192, in render
    return self._render(mode=mode, close=close)
  File "/home/nathaniel/Documents/machinelearning/universe/universe/wrappers/render.py", line 49, in _render
    return self.env.render(mode=mode, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 192, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 342, in _render
    return self.env.render(mode, close)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 192, in render
    return self._render(mode=mode, close=close)
  File "/home/nathaniel/Documents/machinelearning/universe/universe/envs/vnc_env.py", line 533, in _render
    self.vnc_session.render(self.connection_names[0])
go_vncdriver.Error: /tmp/pip-build-y6uWFh/go-vncdriver/.build/src/github.com/openai/go-vncdriver/main.go:387: go_vncdriver was installed without OpenGL support. See https://github.com/openai/go-vncdriver for details on how debug.
`

I have now installed the correct dependencies and gotten it to build with OpenGL, but the program is still running without it. Is there a way to remove go-vcndriver and do a clean install?

**Comment by gdb** [comment]
My usual trick is to entirely remove the code: i.e. find the path with `python -c "import go_vncdriver; print(go_vncdriver.__file__)"` and then `rm -rf </path/...>`. You can then try to `import go_vncdriver` again and make sure it fails.

**Comment by scriptingislife** [comment]
Thanks! That worked, but now after running ./build.sh again I get 
`ImportError: No module named go_vncdriver` 
even though when I run `pip install go_vncdriver` I get 
`Requirement already satisfied: go_vncdriver in /usr/local/lib/python2.7/dist-packages`

**Comment by gdb** [comment]
So two things you can do:

1. `pip install --no-cache-dir --ignore-installed --upgrade go_vncdriver` (basically the hammer approach)
2. `pip install -e /path/to/go_vncdriver` — use your existing on-disk checkout

**Comment by scriptingislife** [comment]
It works! Thank you very much for your help. I think this is my first time installing a program completely from git.

**Comment by html5cat** [comment]
I ran into same issue yesterday, submitted PR https://github.com/openai/go-vncdriver/pull/8

**Comment by jeremyschlatter** [comment]
This is solved for @becksteadn I think the new build instructions in #8 will mostly keep people from stumbling into this issue in the future.
