### ISSUE TITLE
The error "go_vncdriver was installed without OpenGL support" is still existed

### ISSUE THREAD

**Issue by Tbyo** [openai/go-vncdriver#13]
ubantu 14.04, python 2.7
I am trying to install universe, The error occurs: go_vncdriver was installed without OpenGL support.

The output of ./build.sh is 

"zqc@zqc-P453UJ:~/go-vncdriver$ ./build.sh
Env info:

export GOPATH='/home/zqc/go-vncdriver/.build'
export CGO_CFLAGS='-I/home/zqc/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/zqc/anaconda2/include/python2.7'
export CGO_LDFLAGS='/usr/lib/x86_64-linux-gnu/libjpeg.so -L/home/zqc/anaconda2/lib -lpython2.7'
export GO15VENDOREXPERIMENT='1'

Running build with OpenGL rendering.
Building with OpenGL: GOPATH=/home/zqc/go-vncdriver/.build go build -buildmode=c-shared -o go_vncdriver.so github.com/openai/go-vncdriver. (Set GO_VNCDRIVER_NOGL to build without OpenGL.)
# github.com/openai/go-vncdriver
In file included from /home/zqc/anaconda2/include/python2.7/Python.h:8:0,
                 from .build/src/github.com/openai/go-vncdriver/main.go:5,
                 from $WORK/github.com/openai/go-vncdriver/_obj/_cgo_export.c:3:
/home/zqc/anaconda2/include/python2.7/pyconfig.h:1193:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
 #define _POSIX_C_SOURCE 200112L
 ^
In file included from /usr/include/stdlib.h:24:0,
                 from $WORK/github.com/openai/go-vncdriver/_obj/_cgo_export.c:2:
/usr/include/features.h:230:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L"
 ^
The output of pip install -e ./ is:

"zqc@zqc-P453UJ:~/go-vncdriver$ pip install -e ./
Obtaining file:///home/zqc/go-vncdriver
Requirement already satisfied: numpy in /home/zqc/anaconda2/lib/python2.7/site-packages (from go-vncdriver==0.4.17)
Installing collected packages: go-vncdriver
  Found existing installation: go-vncdriver 0.4.17
    Uninstalling go-vncdriver-0.4.17:
      Successfully uninstalled go-vncdriver-0.4.17
  Running setup.py develop for go-vncdriver
Successfully installed go-vncdriver"

When I run the example of universe again in Pycharm with the interperter: /usr/bin/python2.7, the error " go_vncdriver was installed without OpenGL support." is still existed.

$which python
/home/zqc/anaconda2/bin/python

$ /usr/bin/env python -c 'import sys; print(sys.executable)'
/home/zqc/anaconda2/bin/python

**Comment by tlbtlbtlb** [comment]
I think this is fixed by the clarified instructions in https://github.com/openai/go-vncdriver/commit/1a818cd581d86bffdc16fe9cafe9bc1091874f75
