### ISSUE TITLE
Cannot build with OpenGL: "/usr/bin/ld: cannot find -lGL"

### ISSUE THREAD

**Issue by TylerBalsam** [openai/go-vncdriver#14]
Hello,

I followed the troubleshooting steps and installed all dependencies as required in the README. However, upon re-running ./build.py after everything, I receive the following errors:

/build.py Env info:  export GOPATH='/home/tyler/Documents/universe/go-vncdriver/.build' export CGO_CFLAGS='-I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7' export CGO_LDFLAGS='/usr/lib/x86_64-linux-gnu/libjpeg.so -L/usr/lib -lpython2.7' export GO15VENDOREXPERIMENT='1'  Running build with OpenGL rendering. Building with OpenGL: GOPATH=/home/tyler/Documents/universe/go-vncdriver/.build go build -buildmode=c-shared -o go_vncdriver.so github.com/openai/go-vncdriver. (Set GO_VNCDRIVER_NOGL to build without OpenGL.) # github.com/openai/go-vncdriver/vendor/github.com/go-gl/glfw/v3.2/glfw /usr/bin/ld: cannot find -lGL collect2: error: ld returned 1 exit status # github.com/openai/go-vncdriver/vendor/github.com/go-gl/gl/v2.1/gl /usr/bin/ld: cannot find -lGL /usr/bin/ld: cannot find -lGL collect2: error: ld returned 1 exit status  Note: could not build with OpenGL rendering (cf https://github.com/openai/go-vncdriver). This is expected on most servers. Going to try building without OpenGL.

I have all of the Dependencies from the dependency section installed, the files are there, but for some reason it seems to not be linking the -lGL libraries.

OS is Ubuntu 14.04, Nvidia 357 drivers  & GTX 1070.

Any help would be appreciated. 

Thanks,

**Comment by TylerBalsam** [comment]
Took a few hours, but eventually fixed the problem by updating go to 1.7 and running "apt-get install libegl1-mesa libegl1-mesa-drivers xserver-xorg-video-intel libgl1-mesa-dri libglapi-mesa"

Hope this helps anyone else with this problem. See https://github.com/openai/universe/issues/42 for testing purposes.

**Comment by albertstartup** [comment]
I had the same problem as you, all deps installed and still getting that error.
https://techtidings.blogspot.com/2012/01/problem-with-libglso-on-64-bit-ubuntu.html
This fixed it. Builds without a problem.
Didn't have to update Go. 
I dont know why the links in the mesa directory are broken.
I do have the nvidia driver installed.

**Comment by arsenious** [comment]
@albertstartup 

Hi, I'm relatively new to linux. Please could you tell how to adapt that blog post to the go-vncserver issue. I'm not sure on how to fix the broken links. Please can you tell me what the symbolic link should be named and what it should point to. Thanks

**Comment by arsenious** [comment]
@TylerBalsam 

Hi please could you tell me exactly how to upgrade golang to 1.7 ? apt-get already thinks its the latest version. Thanks

**Comment by mmhobi7** [comment]
`export GO111MODULE=off`
