### ISSUE TITLE
inconsistent naming

### ISSUE THREAD

**Issue by level-3** [openai/go-vncdriver#15]
i notice that the package is called both go-vncdriver and go_vncdriver . i think this might be causing issue with the go.exe file with the '-' being read as an option

**Comment by jeremyschlatter** [comment]
Yeah, it seems like it would be good to always call this package go_vncdriver. I haven't seen this lead to errors, though. Do you have a stacktrace for the go.exe problem?

**Comment by tlbtlbtlb** [comment]
The python package is go_vncdriver. The distribution and git repo are go-vncdriver. We do this in other places, like mujoco-py and it doesn't seem to cause problems.
